kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-linstor-provisioner
subjects:
  - kind: ServiceAccount
    name: linstor-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: linstor-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
